version: '3.5'
services:
  flyway:
    container_name: "elite-drive-flyway"
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate -X
    volumes:
      - ../src/main/resources/migrations:/flyway/sql
    depends_on:
      - postgres
  postgres:
    container_name: "elite-drive-postgres"
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}